'use strict';

const REQUIRED_SECRET_KEYS = ['ADMIN_AUTH_SECRET', 'ADMIN_ALTCHA_SECRET'];
const DEFAULT_SECRET_FILE = 'admin-secrets.env';

function ensureAdminSecrets({ crypto, dataDir, env = process.env, fs, path }) {
  const filePath = path.join(dataDir, DEFAULT_SECRET_FILE);
  const fileValues = readSecretFile(filePath, fs);
  const values = { ...fileValues };
  let generated = false;

  for (const key of REQUIRED_SECRET_KEYS) {
    if (hasSecret(env[key])) {
      values[key] = String(env[key]);
      continue;
    }
    if (hasSecret(values[key])) continue;
    values[key] = crypto.randomBytes(48).toString('base64');
    generated = true;
  }

  if (generated || !fs.existsSync(filePath)) {
    writeSecretFile({ filePath, fs, path, values });
  } else {
    secureSecretFile(filePath, fs);
  }

  return {
    env: { ...env, ...values },
    filePath,
    generated,
  };
}

function hasSecret(value) {
  return typeof value === 'string' && Buffer.byteLength(value.trim(), 'utf8') >= 32;
}

function readSecretFile(filePath, fs) {
  if (!fs.existsSync(filePath)) return {};
  const values = {};
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const index = trimmed.indexOf('=');
    if (index < 1) continue;
    const key = trimmed.slice(0, index).trim();
    const value = trimmed.slice(index + 1).trim();
    if (REQUIRED_SECRET_KEYS.includes(key)) values[key] = value;
  }
  return values;
}

function writeSecretFile({ filePath, fs, path, values }) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const lines = [
    '# Auto-generated by UDP Airband Server.',
    '# Keep this file private. These values protect Web Admin sessions and challenges.',
    ...REQUIRED_SECRET_KEYS.map((key) => key + '=' + values[key]),
    '',
  ];
  fs.writeFileSync(filePath, lines.join('\n'), { mode: 0o600 });
  secureSecretFile(filePath, fs);
}

function secureSecretFile(filePath, fs) {
  try {
    fs.chmodSync(filePath, 0o600);
  } catch {
    // Some filesystems do not support POSIX permissions. Startup validation still uses the secrets.
  }
}

module.exports = {
  DEFAULT_SECRET_FILE,
  ensureAdminSecrets,
  readSecretFile,
};
